//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework6.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homework6.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap giphy {
            get {
                object obj = ResourceManager.GetObject("giphy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Copyright 2010-2013 10gen Inc.
        ///*
        ///* Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///* you may not use this file except in compliance with the License.
        ///* You may obtain a copy of the License at
        ///*
        ///* http://www.apache.org/licenses/LICENSE-2.0
        ///*
        ///* Unless required by applicable law or agreed to in writing, software
        ///* distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        ///* See the License for the sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MongoDB_Bson {
            get {
                object obj = ResourceManager.GetObject("MongoDB_Bson", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MongoDB_Bson1 {
            get {
                object obj = ResourceManager.GetObject("MongoDB_Bson1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;MongoDB.Bson&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:MongoDB.Bson.BsonExtensionMethods&quot;&gt;
        ///            &lt;summary&gt;
        ///            A static class containing BSON extension methods.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:MongoDB.Bson.BsonExtensionMethods.ToBson``1(``0)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Converts an object to a BSON document byte array.
        ///            &lt;/summary&gt;
        ///            &lt;typeparam  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MongoDB_Bson2 {
            get {
                return ResourceManager.GetString("MongoDB_Bson2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MongoDB_Driver {
            get {
                object obj = ResourceManager.GetObject("MongoDB_Driver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MongoDB_Driver1 {
            get {
                object obj = ResourceManager.GetObject("MongoDB_Driver1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;MongoDB.Driver&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:MongoDB.Driver.Builders.BuilderBase&quot;&gt;
        ///            &lt;summary&gt;
        ///            Abstract base class for the builders.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:MongoDB.Driver.Builders.BuilderBase.#ctor&quot;&gt;
        ///            &lt;summary&gt;
        ///            Initializes a new instance of the BuilderBase class.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MongoDB_Driver2 {
            get {
                return ResourceManager.GetString("MongoDB_Driver2", resourceCulture);
            }
        }
    }
}
